### ISSUE TITLE
Eigen库中头文件有缺失

### ISSUE THREAD

**Issue by zeroseven-hash** [msraig/CE-PolyCube#1]
您的eigen3文件中core头文件好像缺失了。另外，我在编译运行程序后，好多结果和您在appendix文件中的结果不一致，使用您提供的可执行程序也一样，如3002.hh.sat，我在cut的那一步就失败了，还有一些则是成功的，但是结果没有您appendix文件中那么好，是因为特定的模型需要一些特定的参数嘛？麻烦解答一下我的疑惑，十分感谢

**Comment by guohaoxiang** [comment]
您好。我们的个别例子确实使用了不一样的参数和流程。对3002.hh.sat而言，Feature-awere polycube deform这步可以省略，将模型直接输入PolyCut程序就能得到附录中的polycube结果。割过程中bs（一次切割边数）会影响切割效果，使用更大的bs有时可以提升hex质量。此外个别模型如fandisk还需要调小mr(最小切割深度)为0.3, 以保证所有非特征边都能被切割，但过小的mr会使tetgen出错，请谨慎调参。
