### ISSUE TITLE
请问一下调用HexaRefiner怎么保留边界特征

### ISSUE THREAD

**Issue by zjc0707** [msraig/CE-PolyCube#2]
这是我的输入模型
<img width="590" alt="image" src="https://user-images.githubusercontent.com/54527003/119802169-e9edf480-bf10-11eb-929d-1b4e05e2996a.png">

执行 `./HexaRefiner -i test.vtk  -o out_s.hex` 后得到输出模型
<img width="568" alt="image" src="https://user-images.githubusercontent.com/54527003/119802272-ff631e80-bf10-11eb-846e-477457c2fcf5.png">

请问该如何操作能保留边界特征？
谢谢

**Comment by guohaoxiang** [comment]
您好，为了保持特征，请参考Scripts/gen_hex.bat的流程生成对应的tfe 文件和hfe 文件，然后执行如下命令优化六面体质量：
%HEX_OPT_PATH%\HexaRefiner.exe -e -t 0.4 -i %WORKING_PATH%\%1_cut_ori_hex_merge.vtk -o %WORKING_PATH%\%1_hex_opt.vtk -b %WORKING_PATH%\%1.obj -k %WORKING_PATH%\%1_polycube.tfe -l %WORKING_PATH%\%1_cut_hex.hfe >> %1_log.txt
